const $ = (selector) => document.querySelector(selector);
const state = { points: [], current: null };
const getSettings = () => ({ api: `${location.origin}/api/license`, token: sessionStorage.getItem('icashboxCmsToken') || '' });
const putSettings = () => { sessionStorage.setItem('icashboxCmsToken', $('#token').value.trim()); };
const request = async (path, options = {}) => { const { api, token } = getSettings(); if (!api || !token) throw new Error('Укажите токен администратора.'); const response = await fetch(`${api}${path.replace(/^\/v1/, '')}`, { ...options, headers: { authorization: `Bearer ${token}`, 'content-type': 'application/json', ...(options.headers || {}) } }); const text = await response.text(); let data; try { data = JSON.parse(text); } catch { throw new Error(`Сервер вернул ${response.status}, а не ответ API. Обновите CMS и повторите.`); } if (!response.ok) throw new Error(data.error || 'Ошибка API'); return data; };
const expiry = (date) => new Date(`${date}T23:59:59.999Z`).getTime() < Date.now();
const escape = (text) => String(text || '').replace(/[&<>'"]/g, (char) => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[char]));
function render() { const active = state.points.filter((point) => point.status === 'active' && !expiry(point.expires_at)); const devices = state.points.reduce((sum, point) => sum + Number(point.activation_count || 0), 0); $('#summary').innerHTML = `<article class="metric"><span>Всего точек</span><strong>${state.points.length}</strong></article><article class="metric"><span>Активные лицензии</span><strong>${active.length}</strong></article><article class="metric"><span>Подключённые кассы</span><strong>${devices}</strong></article>`; $('#cards').innerHTML = state.points.length ? state.points.map((point) => { const expired = expiry(point.expires_at); const label = expired ? 'Истекла' : point.status === 'blocked' ? 'Заблокирована' : 'Активна'; const className = expired ? 'expired' : point.status === 'blocked' ? 'blocked' : ''; return `<article class="card"><div class="card-top"><div><h2>${escape(point.name)}</h2><div class="muted">${escape(point.address || 'Адрес не указан')}</div></div><span class="badge ${className}">${label}</span></div><div class="facts"><div><span>Лицензия до</span><b>${point.expires_at}</b></div><div><span>Кассы</span><b>${point.activation_count} / ${point.max_activations}</b></div><div><span>Контакт</span><b>${escape(point.contact || '—')}</b></div></div><div class="card-footer"><button class="link" data-edit="${point.id}">Настроить</button><button class="link" data-reset="${point.id}">Сбросить кассы</button><button class="link danger" data-rotate="${point.id}">Новый ключ</button></div></article>`; }).join('') : '<div class="empty">Точек пока нет. Добавьте первую.</div>'; document.querySelectorAll('[data-edit]').forEach((button) => button.onclick = () => openForm(state.points.find((point) => point.id === button.dataset.edit))); document.querySelectorAll('[data-rotate]').forEach((button) => button.onclick = () => rotate(button.dataset.rotate)); document.querySelectorAll('[data-reset]').forEach((button) => button.onclick = () => resetActivations(button.dataset.reset)); }
async function load() { try { putSettings(); state.points = (await request('/v1/admin/points')).points; render(); } catch (error) { $('#cards').innerHTML = `<div class="empty">${escape(error.message)}</div>`; } }
function openForm(point = null) { state.current = point; $('#formTitle').textContent = point ? 'Настройка точки' : 'Новая точка'; $('#id').value = point?.id || ''; $('#name').value = point?.name || ''; $('#address').value = point?.address || ''; $('#contact').value = point?.contact || ''; $('#expiresAt').value = point?.expires_at || new Date(Date.now() + 31536000000).toISOString().slice(0, 10); $('#maxActivations').value = point?.max_activations || 1; $('#status').checked = !point || point.status === 'active'; $('#pointDialog').showModal(); }
async function save(event) { event.preventDefault(); const point = { name: $('#name').value, address: $('#address').value, contact: $('#contact').value, expiresAt: $('#expiresAt').value, maxActivations: $('#maxActivations').value, status: $('#status').checked ? 'active' : 'blocked' }; try { const result = state.current ? await request('/v1/admin/point', { method: 'PATCH', body: JSON.stringify({ ...point, id: state.current.id }) }) : await request('/v1/admin/points', { method: 'POST', body: JSON.stringify(point) }); $('#pointDialog').close(); if (result.licenseKey) showKey(result.licenseKey); await load(); } catch (error) { alert(error.message); } }
async function rotate(pointId) { if (!confirm('Старый ключ сразу перестанет работать. Создать новый?')) return; try { showKey((await request('/v1/admin/rotate', { method: 'POST', body: JSON.stringify({ id: pointId }) })).licenseKey); await load(); } catch (error) { alert(error.message); } }
async function resetActivations(pointId) { if (!confirm('Сбросить все привязанные кассы? Они смогут активироваться заново.')) return; try { await request('/v1/admin/reset', { method: 'POST', body: JSON.stringify({ id: pointId }) }); await load(); } catch (error) { alert(error.message); } }
function showKey(key) { $('#licenseKey').textContent = key; $('#keyDialog').showModal(); }
Object.assign($('#token'), { value: getSettings().token }); $('#connect').onclick = load; $('#add').onclick = () => openForm(); $('#close').onclick = $('#cancel').onclick = () => $('#pointDialog').close(); $('#pointForm').onsubmit = save; $('#closeKey').onclick = () => $('#keyDialog').close(); $('#copyKey').onclick = async () => { await navigator.clipboard.writeText($('#licenseKey').textContent); $('#copyKey').textContent = 'Скопировано'; setTimeout(() => $('#copyKey').textContent = 'Скопировать', 1300); }; $('#downloadConfig').onclick = () => { const contents = JSON.stringify({ version: 1, type: 'icashbox-online-license', apiUrl: `${location.origin}/api/license`, licenseKey: $('#licenseKey').textContent }, null, 2); const url = URL.createObjectURL(new Blob([contents], { type: 'application/json' })); const link = Object.assign(document.createElement('a'), { href: url, download: 'icashbox-online-license.json' }); link.click(); URL.revokeObjectURL(url); };
if (getSettings().token) load();
